### PR TITLE
Extend EvoSensorMsg with IMU

### PR DESCRIPTION
**Pull request by larsll**
**Issue Number** (if available):

**Description of changes:** Extending the EvoSensorMsg with Imu data. 

--

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by pratik-nichat — COMMENTED** [review]
Hello @larsll,
Thank you for your contribution to DeepRacer Opensource initiative.

Regarding this PR: The imu_data is a sensor_msgs/Imu which doesn’t have to be a custom message type and hence can be imported directly, so I think we can skip extending the EvoSensorMsg since this (EvoSensorMsg) custom message is specifically for the messages to be fed to the neural network during inference.

Suggestion regarding the IMU package: I think a useful approach to make use of [IMU package](https://github.com/larsll/aws-deepracer-imu-pkg) would be to add it in the [AWS DeepRacer](https://github.com/aws-deepracer/aws-deepracer) repository under [deepracer_nodes](https://github.com/aws-deepracer/aws-deepracer/tree/main/deepracer_nodes) since this can provide the ability to use the AWS Deepracer along with the IMU data for a range of applications using ROS2 Integration / otherwise. For example, you can take a look at the [robot_localization package](http://docs.ros.org/en/melodic/api/robot_localization/html/index.html) which can be used to fuse IMU data with other sensor inputs as well to get the state information data which is useful in many robot applications. Do check the orientation of the IMU on the DeepRacer and verify if the imu data fetched is correct with respect to that. 

Let me know if you have any questions or suggestions as well. Thank you.

**Comment by larsll** [comment]
@pratik-nichat - thanks for responding.

Two reasons for putting it into EvoSensorMsg:
* It is a true, embedded, sensor; and goal must be to integrate with the full DR stack, and hence be part of Sensor Fusion Node
* Only if part of a 'joint' message is it possible to correlate picture to movement.

I do have a IMU producing Node ready: https://github.com/larsll/aws-deepracer-imu-pkg -- happy for you to link to it.

**Comment by pratik-nichat** [comment]
Hello @larsll,
1. Can you explain more about the use-case for which the IMU data needs to be a part of EvoSensorMsg? If there is a project idea, we would suggest to create a independent developmental branch on this repository for the same.
2. We shall be happy to link the IMU package developed by you in our [community project list](https://github.com/aws-deepracer/aws-deepracer-launcher/blob/main/community-projects.md). Please go through the documentation requirements taking into reference our existing community projects and make sure all steps are tested and validated on the AWS DeepRacer device.
If you have any other questions, please reach out to us on [deepraceropensource@amazon.com](deepraceropensource@amazon.com)

Thanks,
Pratik

**Comment by larsll** [comment]
I have solved the fusioning of IMU data through a custom message in my own package:
https://github.com/larsll/larsll-deepracer-incar-video-pkg

**Pull request closed without merging**
